### ISSUE TITLE
var has no color

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#114]
This is not a joke

```java
var x = 10;
```

var is supported now, but it has no color.

**Comment by agh2k** [comment]
This issue probably belongs in the [processing-docs](https://github.com/processing/processing-docs) repo since it requires changing keywords_base.txt, which I assume would cause var highlight on Processing 3. Perhaps a branch there for Java 11 support is a solution?

You can manually edit your modes/java/keywords.txt file and add `var	KEYWORD5` in the Datatypes section, as a temporary fix.

**Comment by benfry** [comment]
Fixed for 4.0a3.
