### ISSUE TITLE
Create a core-sources jar

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#118]
This came up from @clankill3r but wanted to check with you @benfry before I did it. It would probably help folks using the core jar as a dependency in Java to have a core-sources jar. That's just adding:

```
<jar basedir="bin" destfile="library/core-sources.jar"> 
    <fileset dir="src" includes="**/*.java"/>
</jar>
```

Have any objections to that?

**Comment by benfry** [comment]
If that goes into `library`, isn't the preprocessor going to auto-add that .jar to the classpath and scan it?

**Comment by benfry** [comment]
Just adding a separate build target for this to core. For folks who want it:

```
cd core
ant source-jar
```

Don't want to include in the download because it's not clear where to put it… do we really tell folks to do Show Package Contents on macOS? Does that help anyone? And I don't want to make it a separate download since I don't need more on my plate when pushing out new releases.
