### ISSUE TITLE
pixelDensity() throws error in setup()

### ISSUE THREAD

**Issue by REAS** [benfry/processing4#127]
Is it the plan for 4.0 to not be able to have pixelDensity() in setup(), or is that a work-in-progress?

**Comment by benfry** [comment]
Inside the PDE, it should work inside `setup()`. In Eclipse/IntelliJ it still needs to live in `settings()`. Is it not behaving?

**Comment by REAS** [comment]
Not right now. In the 4.0a1 it throws the non-PDE error:

```
When not using the PDE, pixelDensity() can only be used inside settings().
Remove the pixelDensity() method from setup(), and add the following:
public void settings() {
  pixelDensity(2);
}
IllegalStateException: pixelDensity() cannot be used here, see https://processing.org/reference/pixelDensity_.html
```

**Comment by benfry** [comment]
Nuts, ok; sounds like I goofed something with those AWT changes.

**Comment by sampottinger** [comment]
Hey friends! @REAS and @benfry this was a bug that was fixed after the first alpha release. It's fixed on master.

**Comment by sampottinger** [comment]
Hey there! Sorry for the re-post... just wanted to double check... This was a bug in the first alpha release that has since been resolved within the PDE. It is working inside master. It will need to be inside settings when outside the PDE.

<img width="957" alt="Screen Shot 2020-08-31 at 9 31 54 AM" src="https://user-images.githubusercontent.com/110391/91743561-d9b90c80-eb6c-11ea-9aec-ec6ec453c3ad.png">

**Comment by sampottinger** [comment]
LMK if this is working for you or not and I can close or work on a fix.

**Comment by benfry** [comment]
Ok, then we should be all set since it looks like @REAS was using alpha 1.
