### ISSUE TITLE
static imports partly broken

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#16]
In 3.5.3 you could use `import static`. 
Here I use it for `Ani.init()` in setup.

```
import de.looksgood.ani.*;
import static de.looksgood.ani.Ani.*;

void setup() {
  init(this);
}
```
I use Ani as an example cause i didn't want to share a whole project to demonstrate.

With processing4 I get:

> No library found for de.looksgood.ani.Ani
> The function init(sketch_191027a) does not exist.

The 'No library found' error is not new, but not being able to use the static methods is new.

!!! I do use the latest release that can be downloaded from Sam Pottinger's site, which is dated September. I'm unable to build it myself.

**Comment by sampottinger** [comment]
Hummm.... Thanks for the issue @clankill3r. I will try to take a look!

**Comment by sampottinger** [comment]
Ah I see what you mean @clankill3r... This has been like half broken (half working?) for a while in mainline processing (https://github.com/processing/processing/issues/5577). :-/ I can think I can fix this! However, I am worried about Ben mentioning it was not supported (I can't find anything in the [official docs](https://github.com/processing/processing/wiki/Supported-Platforms) saying it's not supported but he [left a comment in a bug that it wasn't](https://github.com/processing/processing/issues/5577#issuecomment-406283900)). With the new ANTLR stuff, I don't see any reason on my end not to support it so I'll put a PR up but I'll leave it up to him to decide if it should be supported or if a (better) error should be thrown on encountering static imports. It does mean that import statements need to be tracked as more than just strings internally within the preprocessor and its consumers because some places can't handle anything but the fully qualified name being retained but I don't really see a huge downside to migrating that code. Logic for imports is already isolated within the build pipeline and it seems like it would be safer long term to clarify wildcards versus library name versus fully qualified name. It was confusing for me when I was reading through earlier this year when doing my own edits.

... Either way, there should either be a better error message or support for static imports. It's confusing the way it is.

**Comment by sampottinger** [comment]
Hey there @clankill3r! https://github.com/sampottinger/processing4/pull/19 would resolve your issue. I'll redirect that PR to this branch shortly after a little more testing.

**Comment by sampottinger** [comment]
Sorry one more update @clankill3r. I put in https://github.com/processing/processing4/pull/18. I'll post a new build up on my website in a bit depending on how that PR goes. Thanks for your patience!

**Comment by clankill3r** [comment]
great! Looking forward to the new build.

Op di 5 nov. 2019 om 03:19 schreef A Samuel Pottinger <
notifications@github.com>:

**Comment by sampottinger** [comment]
Hey @clankill3r - this is previewed in a new build. See https://github.com/sampottinger/processing4 (and https://www.datadrivenempathy.com/processing).

**Comment by clankill3r** [comment]
![Screen Shot 2019-11-12 at 10 25 24](https://user-images.githubusercontent.com/738650/68659155-0ac14580-0537-11ea-93e1-1573390d265b.png)

Look at the ugly yet beautifully working button :)
