### ISSUE TITLE
triangle() drawing with NaN values inconsistent with Processing 3

### ISSUE THREAD

**Issue by PixelCatalyst** [benfry/processing4#160]
## Description

I built and tested processing4. I noticed small inconsistency with triangle drawing - if two of the vertices are incorrect (e.g. have x == NaN), the third one is rendered as a point in processing 3.5.4/3.5.3, but the same does not happen in processing 4.x. It may be a small difference (or maybe even expected behavior) but if someone has a sketch depending on some weird triangle manipulations their code may not work in P4 as expected.

Code to reproduce:
```
void setup() {
  size(500, 500);
  
  strokeWeight(50);
}

void draw() {
  background(255);
  
    float d = 233.0 / 0.0;
    triangle(d,-250, d,260, 250,270);
}

```

## Expected Behavior

![Processing 3 - expected](https://user-images.githubusercontent.com/34219846/105404181-f7753400-5c29-11eb-8f52-059a161bb436.jpg)

## Current Behavior

![Processing 4 - actual](https://user-images.githubusercontent.com/34219846/105404204-fe9c4200-5c29-11eb-9510-111282f9034e.jpg)

## Your Environment

 

* Processing version: Processing4 built up to commit e96622d63
* Operating System and OS version: Windows 10 build 19042.685

**Comment by dzaima** [comment]
`JAVA2D` on Processing 4 does what `FX2D` did in Processing 3, and it's inconsistent with `P2D` too (which does its own magic). I don't think there's any value in keeping such things consistent, there are many _much_ bigger changes between Processing 3 and Processing 4 that would break projects millions of times over before this does.

**Comment by benfry** [comment]
Thanks for the report. I don't think we want to make the bug consistent across renderers here.

The real fix would be to warn users when `NaN` values are sent to graphics methods, but that's a lot of code in a lot of places (basically any time a position or color or… anything? is passed…) so that's probably more overhead than we want to address at the moment. 

(Tempting, though, given our audience, and how tricky it can be to debug this sort of thing in your code. There's such a check in `map()` since it's so common to hit it there, but we've not really done it elsewhere.)
