### ISSUE TITLE
Make macOS notarization part of the build process

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#24]
Currently there is a mechanism for signing the Processing app for Mac but we don't currently notarize which will be required in January. See https://developer.apple.com/news/?id=09032019a and https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow.

**Comment by benfry** [comment]
Hooray.

**Comment by benfry** [comment]
And this one gets more serious in a month… https://developer.apple.com/news/?id=12232019a

**Comment by sampottinger** [comment]
Yeah I saw :(

I have a developer ID that I've been using for the existing builds I've been posting. I will give this a shot soon. It looks like it is possible (even if it is annoying) to notarize from the command line: https://blog.zeplin.io/dev-journal-automate-notarizing-macos-apps-94b0b144ba9d. Considering this in combination with #25, we should chat offline...

**Comment by benfry** [comment]
Ok, managed to get this working by hand… We'll see if it actually works. 🤢

**Comment by benfry** [comment]
3.5.4 was notarized, though I haven't tested much to see if/how it worked. 

Didn't bother with notarizing 4.0a1 since we'll probably need an alpha 2 before the deadline arrives. 

The magic incantation was:

```
xcrun altool --notarize-app \
             --primary-bundle-id "org.processing.app.zip" \
             --username "$APPLE_EMAIL" \
             --file macosx/processing-3.5.4-macosx.zip
```

Where `APPLE_EMAIL` was the email address for my Apple (Developer) ID account. 

This prompts for password, but the password can be provided on the command line with `--password` as well. 

It was also necessary to create an app-specific password inside the Account Settings. The “name” of the application specified isn't used for anything, only the password matters. The real account password won't work in this context.

If things work properly, `xcrun altool` will spit out a UUID that can be used to check status.
