### ISSUE TITLE
Imports whose name contains "color" cause Syntax error

### ISSUE THREAD

**Issue by micycle1** [benfry/processing4#240]
## Description
Imports whose name contains "color" cause a syntax error since Processing interprets these as the `color` datatype.

![image](https://user-images.githubusercontent.com/9304234/128710835-9819e00e-875f-4ed3-9522-402b2541d233.png)

## Your Environment
* Processing version: 4.0 Beta 1
* Operating System and OS version: Windows 10

**Comment by benfry** [comment]
Hm, that's unfortunate, though I'm not sure it's a bug—does that work with `int`, `float`, or any other primitive types? `color` is what's considered a “reserved word” in the language.

(Edited to add: if it was working in 3.x, that was probably a bug in the preprocessor, unfortunately.)

**Comment by micycle1** [comment]
It was working in 3.x.

![image](https://user-images.githubusercontent.com/9304234/129017193-31a699f4-6451-4a9f-bef8-734c37594bff.png)

![image](https://user-images.githubusercontent.com/9304234/129017265-fd5e2c7b-1dd6-4ae7-927c-4730fb2cadc5.png)

**Comment by sampottinger** [comment]
I’ll look into this right away @micycle1. Thank you for reporting it.

**Comment by sampottinger** [comment]
Apologies @benfry and @micycle1 for not having seeing this during the alpha testing. Color is a little strange because, gramatically, it shouldn't be able to appear in a fully qualified name (or import) like int cannot. However, I would hate to have any incompatibility. @benfry, I'm suggesting a change to the grammar. Please see #246.
