### ISSUE TITLE
Fatal Error on P3D vertex call

### ISSUE THREAD

**Issue by merttoka** [benfry/processing4#243]
## Description

I run two sketches in a Java application. The draw commands are mostly the same between the two versions; the only difference is that the second one draws everything in 3D space with PeasyCam enabled. When I run the `.vertex(x,y,z)` command for a `PShape` on the second sketch, the whole Java application crashes without any error message. I can see the line drawings for half a second before the application closes. I tried to track the reason for the crash in my code but it seems like it's running fine until I enable [this line in the repository](https://github.com/move-ucsb/DynamoVis/blob/spacetimecube-dev/src/main/Box.java#L353). I couldn't find any NaNs or infinities in the coordinates as well. 

I also reproduced the same behavior using Processing 4 beta 1 IDE, you can find [the gist here](https://gist.github.com/merttoka/84cc0c591f029d6f5abc1ce46952a05a).

## Expected Behavior

I believe this is a bug from Processing and I wish I could highlight where it's originating. I was expecting to see the rendering of my path as I am seeing in my first sketch.

## Current Behavior

Crash at the vertex call of the second sketch. 

## Steps to Reproduce

Here is [a rough gist](https://gist.github.com/merttoka/84cc0c591f029d6f5abc1ce46952a05a) that replicates the error with shorter lines of code:
1. Change the iteration number to 20 on both files -- it works 
2. Change them to something like 1000 -- it crashes

## Your Environment

 

* Processing version: Processing 4-beta 1 (the problem existed with Processing 4-alpha 6 as well)
* Operating System and OS version: Windows 10.0.19043 
* System Type: x64-based PC
* Processor: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz, 3696 Mhz, 10 Core(s), 20 Logical Processor(s)
* GPU: NVidia RTX 3080
__I can provide more system information if necessary__

## Possible Causes / Solutions

I wish I knew how to fix this issue. I can try to help if you can point me in the right direction.

**Comment by codeanticode** [comment]
I tested the code in your gist with Processing 4b1, and did not see any crash, even increasing the vertex count to 10,000. I did get a 'OpenGL error 1282 at top endDraw(): invalid operation' error a few times though, but this error does not typically affecting the drawing. 

However, the use of PShape in your code is not recommended, because you are creating a new PShape object in each frame (this is similar to placing a loadImage() call inside draw()), in a situation like this, where the shape's vertices changes in each frame, you should just re-draw the shape:

```
void setup() {
  size(800, 800, P3D);
  colorMode(HSB, 360, 100, 100);
  frameRate(60);
}

void draw() {
  background(0);

  beginShape();
  noFill();
  strokeWeight(5);
  stroke(255, 150);
  for(int i=0; i< 1000; i++) {
    vertex(width/2, mouseY+i*20, height/2);
  }
 endShape();
}
```

There is a new feature currently being tested (https://github.com/processing/processing4/issues/196) that would enable this use scenario with PShape objects, by allowing you to change the coordinates of a PShape after creation using setVertex() in a performant manner. You can currently modify a PShape using setVertex(), setFill(), and the like, but these functions can slow down the sketch significantly because  internally re-tessellatate the geometry.

**Comment by merttoka** [comment]
Thanks for the quick reply. I confirm that the issue was creating multiple PShape objects in every frame. Unfortunately, I am building an already existing codebase, and I missed that spot. 

Apologies for the inappropriate bug report. I highly appreciate the work you have been doing. Looking forward to the PShape with buffer object streaming.
