### ISSUE TITLE
There are no build instructions

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#26]
I wanted to gave it another attempt at building cause I need to set some JVM options.
However, the build instructions are gone.
After some effort I did found them here:

https://gist.github.com/sampottinger/939441d7277d318189ec81844e3ca516

But It's a bit hidden.

**Comment by sampottinger** [comment]
@benfry where would you like these to live?

**Comment by benfry** [comment]
For the short term, let's save your file as `README.md` at processing/build. That'll at least give us a place to work on it a bit. 

(Eventually all or part or a link to it should live in a spot that doesn't require pulling the repo, since that's part of the point of build instructions… but we can figure that out later.)
