### ISSUE TITLE
is processing4 available in a maven repository?

### ISSUE THREAD

**Issue by maxandersen** [benfry/processing4#262]
## Description
processing 3.x is available in maven under org.processing:core:3.3.7.

Where are the 4.x published to ? Would like to use them directly from java
using standard build tools. thank you.

**Comment by maxandersen** [comment]
fyi, based on https://discourse.processing.org/t/processing-4-core-maven-artifact/27334/2 I made https://github.com/maxandersen/processing4/tree/jitpack which enables using jitpack for building and fetching maven dependencies.

Example using jbang.dev:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
// //DEPS <dependency1> <dependency2>
//REPOS jitpack,mavencentral
//DEPS com.github.maxandersen:processing4:jitpack-SNAPSHOT
//processing relies on mac specific classes removed in Java 10 and highger
//https://discourse.processing.org/t/error-hello-processing-jdk-10-osx-high-sierra-com-apple-eawt-quithandler-not-supported/1396/3
// JAVA 8

import processing.core.PApplet;
import processing.core.PVector;

import java.awt.*;

import static java.lang.Math.max;
import static java.lang.System.*;
import static processing.core.PApplet.cos;
import static processing.core.PApplet.mag;
import static processing.core.PApplet.pow;
import static processing.core.PApplet.sqrt;
import static processing.core.PConstants.TWO_PI;

import java.awt.Polygon;


public class purplerain extends PApplet {

    // Depth sorting example by Jakub Valtar
// https://github.com/JakubValtar


    @Override
    public void settings() {
        size(640, 720, P3D);

    }

    public void setup() {
        colorMode(HSB, 100, 100, 100, 100);

        frameRate(60);
    }

    public void draw() {
        //beginRaw(PDF, "output" + frameCount + ".pdf");

        if (!mousePressed) {
            hint(ENABLE_DEPTH_SORT);
        } else {
            hint(DISABLE_DEPTH_SORT);
        }

        noStroke();

        background(0);

        translate(width/2, height/2, -300);
        scale(2);

        int rot = frameCount;

        rotateZ(radians(90));
        rotateX(radians(rot/60.0f * 10));
        rotateY(radians(rot/60.0f * 30));

        blendMode(ADD);

        for (int i = 0; i < 100; i++) {
            fill(map(i % 10, 0, 10, 0, 100), 100, 100, 30);

            beginShape(TRIANGLES);
            vertex(200, 50, -50);
            vertex(100, 100, 50);
            vertex(100, 0, 20);
            endShape();

            rotateY(radians(270.0f/100));
        }

        //endRaw();

        if (frameCount % 30 == 0) println(frameRate);
    }

    public static void main(String... args) {
        PApplet.main( "purplerain", args);
    }
}
```

What is important ( at least on OSX ) is to use Oracle/JAVA.net JDK which you can get using jdkman `sdk install java 11.0.2-open`

if that is in place then the code above runs using: `jbang purplerain.java`

**Comment by ThexXTURBOXx** [comment]
I think, this would be great for a PR. I, personally, use Processing in many of my projects and still rely on this `<scope>system</scope>` hack :)
But, let's hear the maintainers' opinion on this :)

**Comment by marko-radosavljevic** [comment]
Yeah, every time I create new processing project, I check if maven artifact exist, and check latest news in processing repo. ^^

Maintainer opinion on this is, sadly, pretty clear:  https://github.com/processing/processing/issues/5666

> It's not done officially. I wish people wouldn't do it, because now I'm spending time answering questions about a release that's not supported. Which is… not supported because I don't have the time.

> It's not supported since I don't have time, and nobody's volunteered to support it consistently.
I wish folks wouldn't post it there because then the bug reports about it being broken still come to me. Like this one. And many others, i.e.: #5666

Latest two issues and community discussions on this topic:
https://github.com/processing/processing/issues/6138
https://github.com/processing/processing/issues/6006

> processing 3.x is available in maven under org.processing:core:3.3.7.

This is not official, it's not being updated, and not endorsed by the processing project.

What motivated me to reply to this issue is the fact that I had to debug a friend's processing project today, and the issue was stale and unofficial maven artifacts :/. Hopefully things will change for processing 4. :heart:

**Comment by BenjaminHolland** [comment]
re: The responses mentioned here?
What exactly are the responsibilities and time commitment for helping to maintain this? I'm interested in helping, but I'm not sure how to contact anybody to discuss.

**Comment by davidpc-te** [comment]
A more up to date unofficial option:
https://processing-for-maven.netlify.app

**Comment by benfry** [comment]
Support for a Maven release would mostly be about setting something up that extends the build process so that the artifacts can be created as part of `build/build.xml` calling out to a separate Ant-based `build/maven/build.xml` that creates the necessary files and uploads them. 

In the meantime, I'm looking into having the current unapproved Maven artifacts removed because of all the confusion they're causing. It's frustrating for me because I don't have time to support a Maven release, and have been really clear about that, and now I'm forced into dealing with the unapproved post to Maven Central and spending time I don't have getting the unapproved posting removed. Help me out here, folks…

Updated to add: closing this for now; if someone wants to do the work outlined above, please set it up as a PR and we can see about making it work.
