### ISSUE TITLE
ant build and run fail because ffmpeg is missing in downloads folder

### ISSUE THREAD

**Issue by emlama** [benfry/processing4#319]
## Description
It looks like the [downloads folder for ffmpeg](https://download.processing.org/ffmpeg/4.4/) is missing a target for M1 macs (`aarch64`). I'm getting this when I run `ant build`.

```
download-ffmpeg:
      [get] Getting: https://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz
      [get] To: /Users/esaforrian/src/processing4/build/shared/tools/MovieMaker/ffmpeg-4.4.gz
      [get] Error opening connection java.io.FileNotFoundException: https://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz
      [get] Error opening connection java.io.FileNotFoundException: https://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz
      [get] Error opening connection java.io.FileNotFoundException: https://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz
      [get] Can't get https://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz to /Users/esaforrian/src/processing4/build/shared/tools/MovieMaker/ffmpeg-4.4.gz

prepare-ffmpeg:

BUILD FAILED
/Users/esaforrian/src/processing4/build/build.xml:260: The following error occurred while executing this line:
/Users/esaforrian/src/processing4/build/build.xml:355: The following error occurred while executing this line:
/Users/esaforrian/src/processing4/build/shared/tools/MovieMaker/build.xml:53: the archive ffmpeg-4.4.gz doesn't exist
```

## Expected Behavior
The file downloads correctly.

## Current Behavior
The build fails.

I'm not sure how that downloads folder is maintained, but in the meantime, I was able to unblock myself by pointing my `build.xml` at `https://evermeet.cx/ffmpeg/`.

## Steps to Reproduce
1. Run `ant build` on an M1 Macbook Pro

**Comment by pr1metine** [comment]
Hi @emlama and anyone else reading,
had the same problem you had. Since the developer behind ffmpeg outright [refuses to support ARM devices](https://evermeet.cx/ffmpeg/apple-silicon-arm), this issue has to be resolved upstream.

As pointed out by you, one could just use the x64 ffmpeg binaries without any apparent drawbacks. As a temporary workaround, I would therefore advice the devs behind processing to make a copy of `http://download.processing.org/ffmpeg/4.4/ffmpeg-macos-x86_64.gz` and paste it to `http://download.processing.org/ffmpeg/4.4/ffmpeg-macos-aarch64.gz`.

**Comment by benfry** [comment]
Ah, actually the bug here is that the `build.xml` file is using `os.arch` to determine the download, rather than the architecture that you're building for. Since on M1 we're still building x86_64, it should be using that instead—at least until we can support Apple Silicon. See https://github.com/processing/processing4/issues/128#issuecomment-864532175 for that status.

**Comment by pr1metine** [comment]
Ahh, makes sense. I could also work on porting Processing to Apple Silicon. No promises although I am going to try my best.

**Comment by benfry** [comment]
Ok, just checked in a change that should handle this properly.
