### ISSUE TITLE
Built in translate() function fails to render strokes when the argument exceeds threshold w/ P2D

### ISSUE THREAD

**Issue by AngelStat** [benfry/processing4#341]
## Description

For some reason the built in translate() function causes draw strokes to render improperly or not at all if the P2D renderer is used and the magnitude of the translation is around 33000 or greater. The default renderer as well as P3D did not reproduce the issue on my hardware. The issue only seems to occur if the strokeWeight() is set to a value greater than 1. 

I also got the following error report in the console by increasing both arguments of translate at the same time (I.e. translate(val,val) where val exceeds 33000):
`Tessellation Error: gluTessBeginContour() must precede a gluTessEndContour()`

This particular error does not occur if only one argument of translate is incremented.

For whatever reason this issue does not appear affect fills (based on my personal testing).

## Expected Behavior

A black square stroke rendering properly.

## Current Behavior

Once the translated amount reaches around 33000 the stroke distorts and begins to scrolls off screen.

## Steps to Reproduce

1. Set the renderer to P2D
2. Translate by a value greater than 33000
3. Set strokeWeight to a value greater than 1
4. Draw something with a stroke

```

float val = 32500;

void setup(){
  size(400,400,P2D);
}

void draw(){
    val += 1;
    background(125);
    translate(0,val);
    strokeWeight(2); noFill();
    rect(100,100-val,100,100);
}

```

## Your Environment

 

* Processing version: 4.0b2 and 3.5.4,
* Operating System and OS version: Windows 10 Build 19042
* Other information:

## Possible Causes / Solutions

Just a pure guess but there must be some numerical inaccuracy in what translate is doing and inputs of 33000 and up cause it to start to become noticeable.

**Comment by benfry** [comment]
Most graphics/display systems have a limit around 32k… It's not a Processing bug, it's just a limitation of one of the layers beneath it, whether OpenGL, or the operating system, or whatever. You just have to work with coordinates in a more manageable range, and use `scale()` judiciously. There aren't 32k pixels in either direction on the display after all.

(The 32k is because 2^16 is 65536 unsigned, so most coordinate systems top -32768 to 32768, or a signed 16-bit number.)
