### ISSUE TITLE
size of Processing

### ISSUE THREAD

**Issue by lee2sman** [benfry/processing4#346]
Please forgive this question, and let me know if there's a more appropriate place to ask about this or have a discussion. I wasn't sure where the appropriate place to ask/discuss this is. Processing 3.5 was about 130mb. The current download zip version is 475mb. 

Granted storage is cheaper than ever, there is still an impact of having large program size. This is particularly of concern for students working with budget equipment/small hard drives, but also those coming to Processing using older and lower-powered machines or wanting to use less resources.

Is this a design decision that was intentionally made or a result of particular software needs? Is this of concern only to a few folks like myself and/or not addressable, or is there some way to consider this when making design decisions?

Thank you

**Comment by benfry** [comment]
Yeah, it's not good. I'm acutely aware of concerns about limited hardware. The main problem is that the JavaFX library is enormous, so here's an issue to track that: https://github.com/processing/processing4/issues/348

Bottom line is that I don't like it either, and hope to fix it; it just requires a lot more time that I haven't had.

**Comment by dzaima** [comment]
Of the 880MB of unpacked Processing 4, 278MB is the packaged Java runtime, 445MB is JavaFX, 76MB is ffmpeg for MovieMaker. That leaves 81MB of many more libraries and Processing itself.

Of the 308MB of unpacked Processing 3, 234MB is the packaged Java runtime, and there's no ffmpeg nor separate JavaFX.

The JavaFX in Processing 4 (for linux at least) appears to bundle javafx for all of windows, mac, and linux, so that 445MB could be dividable by 3 if wanted?

**Comment by lee2sman** [comment]
Thanks for weighing and addressing all this! I can see it bothers you too. One other thing to consider I believe is size of the theme selector as well?
