### ISSUE TITLE
Cannot open sketch from double click, Processing 4.0b3

### ISSUE THREAD

**Issue by knupel** [benfry/processing4#347]
Is not possible to open sketch from desktop with double-click on file. That's work fine with Processing 4.0b2. Fortunately we can still open it from `command + O`or from Processing apple menu bar :)

Configuration : OS Monterey / Mac Book Pro 2018 / Processor Intel

**Comment by benfry** [comment]
Bummer, I tried to set the Content Type on the files so that QuickLook would be able to view `.pde` as text files (if no other handler was available) and `pdex` and `pdez` as zip archives, but that wiped out the extension handling. Looks like an appbundler bug, so I'm just shutting it off for beta 4.
