### ISSUE TITLE
java.lang.NoSuchMethodError: accessibilityHitTest but sketch still functions

### ISSUE THREAD

**Issue by tmatinla** [benfry/processing4#368]
## Description

After starting and whenever I click somewhere in PDE, an error
`java.lang.NoSuchMethodError: accessibilityHitTest`
is shown in the Console

This started with beta 3, so it might be due to Java version upgrade.

## Environment

 

* Processing version: 4.0b3
* Operating System and OS version: macOS Monterey (12.1)
* Other information: Intel Mac

## Possible Causes / Solutions

There's a similar issue in this SO question: https://stackoverflow.com/questions/70112706/java-lang-nosuchmethoderror-accessibilityhittest
The discussion refers to this issue: https://bugs.openjdk.java.net/browse/JDK-8274326 that is fixed in 17.0.2, so it might help to upgrade to that when it is available (https://github.com/adoptium/adoptium/issues/109 for tracking the release).

**Comment by benfry** [comment]
As mentioned over in #408, this seems to still be a problem even though beta 6 is using Java 17.0.2. 

And as noted above, the `accessibilityHitTest` issue is a problem inside Java, see:
https://bugs.openjdk.java.net/browse/JDK-8274326
and this is the issue claiming that it's fixed in 17.0.2 b1:
https://bugs.openjdk.java.net/browse/JDK-8274604
…but still no luck. 

Will keep this open so that folks can find it, but at least it doesn't seem to be affecting anything.

**Comment by retiutut** [comment]
https://bugs.openjdk.java.net/browse/JDK-8283347

@benfry This recent issue claims that it cannot be reproduced in JDK 18 and 19. Is it possible to push Processing 4 to one of these?

From my testing, this seems limited to macOS. It really does dirty up the console logs when looking through user interactions.

Take Care,
RW

**Comment by benfry** [comment]
Added code to suppress the error (assuming this was coming through as red text) for 4.0 beta 8.

Still not sure why people are seeing this with beta 6 and later, which use 17.0.2. I haven't seen it.
