### ISSUE TITLE
Race condition when using fill() while a separate thread uses color() / etc

### ISSUE THREAD

**Issue by dgray001** [benfry/processing4#431]
## Description
Apparent race condition between calling fill() and actually drawing something while a separate thread is using color()

## Expected Behavior
Rectangle should be filled green.

## Current Behavior
Rectangle is filled red if fill(green) is called while the separate thread is calling color(red).
![test1](https://user-images.githubusercontent.com/93948143/156501712-dcdd8e69-68c9-4359-a01b-9124cee7ede1.gif)

## Steps to Reproduce
Occurs in this sketch. Comments detail specific requirements to reproduce.

```
class TestThread extends Thread {

  TestThread() {
    super("test");
  }

  @Override
  void run() {
    //delay(1000); // blinks one frame per run() called, can use this to make blinks longer apart
    for (int i = 0; i < large_number; i++) { // blinks if this is still running when fill is called
      color(255, 0, 0);
    }
  }
}

TestThread thread = new TestThread();
int large_number = 1080 * 1920; // like if I wanted to process an image the size of a laptop screen

void setup() {
  fullScreen();
  imageMode(CORNER);
  rectMode(CORNERS);
}

void draw() {
  fill(0, 255, 0); // No blinking if fill isn't called here
  color(255, 0, 0); // obviously this doesn't cause a visual bug
  rect(0, 0, 400, 400);
  if (!thread.isAlive()) {
    //delay(500); // blink occurs on this frame, can use delay to make it longer
    thread = new TestThread();
    thread.start();
    //while(thread.isAlive()) {} // if the thread is allowed to run no blinking occurs
  }
}
```

## Your Environment

 

* Processing version: 4.0b6
* Operating System and OS version: Windows 11
* Other information:

## Possible Causes / Solutions
Seems to be some relation between fill() and color(). After a cursory look at the code base I didn't figure it out so made a hack:
Can get around it if you know the integer value color() will return so I just use the simple function below to return that int. Of course this assumes you aren't using colorMode, etc, but that can be easily added in.

```
int ccolor(int gray) {
  return ccolor(gray, gray, gray, 255);
}
int ccolor(int gray, int a) {
  return ccolor(gray, gray, gray, a);
}
int ccolor(int r, int g, int b) {
  return ccolor(r, g, b, 255);
}
int ccolor(int r, int g, int b, int a) {
  int max = 256;
  return max * max * max * a + max * max * r + max * g + b;
}
```

**Comment by dzaima** [comment]
It's because of [`colorCalc`](https://github.com/processing/processing4/blob/1eefbe0b877f6ec5aabff91d842c7f6e29424145/core/src/processing/core/PGraphics.java#L7759-L7894) used [in the impl of `color()`](https://github.com/processing/processing4/blob/1eefbe0b877f6ec5aabff91d842c7f6e29424145/core/src/processing/core/PGraphics.java#L7911-L7925) and [in `fill()`](https://github.com/processing/processing4/blob/1eefbe0b877f6ec5aabff91d842c7f6e29424145/core/src/processing/core/PGraphics.java#L6904-L6907) (and anything else taking color as user input), which store their results as globals, presumably to avoid allocating an object due to wanting to return many values, which'd be very slow. The PGraphics methods just aren't meant to be multi-threaded.

**Comment by benfry** [comment]
That's correct: it's (primarily) a performance tradeoff. While the performance difference may be less important today than when it was first implemented many years ago, it's not possible to draw from multiple threads anyway.

One possible change would be making `color()` use its own variables so it could be threaded, but I'm not sure whether the utility of this outweighs the extra mess. That introduces another inconsistency, because the function is affected by state set by `colorMode()`, which itself would remain single threaded because it is tied to the `fill()` and `stroke()` methods that are part of single-threaded rendering.

Overall probably a better solution is to add your own method to make the color… In most cases, it's just being used as a convenience to convert rgb values in the range 0…255, which is a one liner:

```java
int c = 0xFF000000 | (r << 16) | (g << 8) | b;
```

and if it's doing anything fancier than that (using `colorMode()`), you're gonna have problems anyway because that affects drawing state and should only be used from the rendering thread (i.e. inside `draw()`). 

So now you're thinking about setting colors and ranges and state, which starts to sound like… a class! Which is likely a better approach for your project if you need something more elaborate than the one-liner above.

**Comment by dgray001** [comment]
Thank you both of you.

**Comment by benfry** [comment]
Thanks for understanding.
