### ISSUE TITLE
Add some information to the readme file

### ISSUE THREAD

**Issue by arnoudvanderleer** [benfry/processing4#450]
The `/README.md` file currently is mainly aimed at people who already know what Processing is and roughly how it works, and is mainly a changelog. It would benefit new developers to have a bit of an explanation of what Processing is and how it works and maybe a small guide to the layout of the repository and/or links to other materials like `processing.org`, `CONTRIBUTING.md` etc.

If I have time, I will make a draft for this in the near future, if you want me to.

**Comment by benfry** [comment]
That's intentional; we have a massive site where we've put a ton of work into getting folks up and running. This is just the repository for the source code. It's not like a library that you might check out the code to include it with your project. 

To avoid confusion, I've added some notes to clarify this in https://github.com/processing/processing4/commit/a4c1d94646f73b4cea5483324bb56a8bb7bcdf1e
