### ISSUE TITLE
JOGL 2.4

### ISSUE THREAD

**Issue by sampottinger** [benfry/processing4#46]
It looks like [JOGL 2.4 is getting further along](http://forum.jogamp.org/JogAmp-Jbeil-RC-Build-2-4-0-rc-20200106-td4040244.html)! I know that there's some work to cut over to LWJGL but we should decide if we want to adopt JOGL 2.4 / if there will be available modes in both?

**Comment by benfry** [comment]
That would be positive… It'd be nice to break fewer things in 4.x and introduce LWJGL as an option.

**Comment by benfry** [comment]
Picking back up from our email discussion, I've opted to remove the JOGL binaries from the repo, and have them auto-download on build. 

I've added `clean-jogl` as an `ant` target so that `ant clean` doesn't wipe out the files, and force you to reconnect to the internet in order to build. (Times that I can do Processing development often coincide with not having limited internet access… flights, other travel, breaks, etc.)

So the current RC is now auto-downloaded, and we can just swap it to the final when we're ready.

**Comment by neilcsmith-net** [comment]
@sampottinger is there more work ongoing with LWJGL? Was in touch with Andres on the Gitter chat on this but gone quiet.  Relevance here?  It would be useful to abstract OpenGL so that the JOGL implementations are in a separate package / JAR too?

**Comment by benfry** [comment]
Closing this since it was resolved in alpha 1: we've integrated the 2.4 RC in alpha 1 and have a means to update to the final once it's available.
