### ISSUE TITLE
Double-clicking a .pde file also opens an untitled/empty sketch

### ISSUE THREAD

**Issue by billv923** [benfry/processing4#477]
## Current Behavior
Double clicking on a .pde sketch file launches the Processing IDE and opens the selected sketch as expected but also opens a second blank sketch. This started happening in Version 4 beta7. Doesn't happen in Version 4 beta6. See attached video.

https://user-images.githubusercontent.com/102330834/164946233-0705a251-b006-47f1-8033-8c6000b63c66.mov

## Steps to Reproduce
1. Double click on any .pde sketch file

## Your Environment
Windows 10 w/ Processing4 beta7 

## Possible Causes / Solutions
Unknown

**Comment by ExpandingS** [comment]
@benfry This was introduced in 59aa860686875385090a2fc97947617a77ec7f2f, with:
```diff
Line 1493:
-      if (props != null) {
+      if (!props.isEmpty()) {
```

Changing it back fixes it, but I don't understand enough about this file to know if that's a reasonable solution, or if isEmpty() should be changed.

**Comment by benfry** [comment]
Thanks @ExpandingS… Though I think that might be a red herring. 3.5.4 does this too (at least on macOS). I may have fixed it in the 4.x series, then removed the code that allowed a file being opened to take over (or at least close) the untitled window that's opened by default, because it's a little trickier than one might expect to determine user intent there.

This is only happening when Processing is not already running, correct?

**Comment by guilhermesilveira** [comment]
The `handleOpen` method was returning null by default after dealing with exceptions. This allowed the Java compilation phase to accept a handleOpenInternal invocation without an explicit `return`. The commits solve the issue by adding the missing `return` and avoids further errors by moving the `return null` statement to inside the exception handler.

**Comment by benfry** [comment]
Thanks all, @guilhermesilveira has found the fix for us. Appreciate the help!
