### ISSUE TITLE
Launch() function does not work

### ISSUE THREAD

**Issue by Logenleedev** [benfry/processing4#496]
**Objective:**

I want to activate/run another processing script using controlp5 button. When users click the button, they can trigger the target script.

**What I have so far:**
Here is my code:

```
import controlP5.*;

void setup(){
  new ControlP5(this).addButton("launchSketch").setLabel("launch\nsketch")
  .setSize(100, 100).setPosition(0,0);
}

void draw(){}

void launchSketch(){
  print("Hi");
  launch("processing-java","--sketch=/absolute/path/to/targetSketch.pde","--run");
}
```

**Issues**:
1. The button works fine. However, when I click it, nothing happens. No script is launched. But I can see "Hi" in my Processing terminal so we know that launchSketch() function is triggered
2. I also tried exec() function, turns out it will just crash the application. 

**System I am using:**
Mac M1, Processing 4; But I also tried my non-M1 mac with Processing 3. Not working.

**Comment by benfry** [comment]
`launch()` works just fine. Try this:

```processing
launch("/Applications/Pages.app");
```

To see what's going on with your code:

1. Put the full path to `processing-java`, because the system probably doesn't know where to find it.
2. Try launching something else to see if it works so you can determine whether it's a problem with `launch()` or with how you're calling `processing-java`. 

A third option would be that there may be macOS security issues, but since the Pages.app example above works on the latest Monterey on an M1 Mac, it should be fine.
