### ISSUE TITLE
Memory leak from blank sketch

### ISSUE THREAD

**Issue by einarOttestad** [benfry/processing4#516]
I have a memory leak problem on a sketch running on a rPi, which will eventually make it crash since the program is running 24/7. Managed to recreate it on my Mac (MacBook Air M1, 2020 Monterey 12.3.1). Processing ver 4.0b8
Found out it happens even with the empty sketch below:

```
void setup(){
  size(100,100);
}

void draw(){
  background(0);  
}

```
Running this, will cause Memory usage to slowly rise, more than 100Mb per hour.
If I reduce frameRate, the memory leaks slower, so it seems to have something to do with the draw() call.

I have also tested it on a PC with Windows 10 Pro 64bit, Processing ver 4.0b1, and got same problem.

I checked memory usage with Activity Monitor on Mac, and Task Manager on PC and rPi.

**Comment by benfry** [comment]
Just to make sure I understand, *that exact code* will cause it to crash within an hour on the Mac? 

Memory usage going up and actually crashing are (confusingly) two different things (i.e. your test case may also have memory going up, but may not crash). The memory usage may go up because the garbage collector isn't clearing out unused memory because plenty of memory is still available. Just want to make sure the test case above actually causes a crash after an hour, not just that the memory is increasing.

**Comment by einarOttestad** [comment]
The rPi-program crashes within maybe four days, not an hour. The little sketch on the mac and PC I have only tested for a few hours and been watching the memory as it goes.

"The memory usage may go up because the garbage collector isn't clearing out unused memory because plenty of memory is still available." - This might have been confusing me! Then probably the behaviour on Mac and PC is all good. 

I still have the program crashing on rPi after aproximatly four days, but that I have to investigate that further.

Thanks for now :-)

**Comment by benfry** [comment]
Ok, thanks for the update. Good luck!

**Comment by dzaima** [comment]
An `if (frameCount%(60*60*10) == 0) System.gc();` in `draw` should make the application force-GC every 10 minutes (assuming 60fps), as a way to discount Java memory management from being the cause of increasing RAM usage. (I have some (non-Processing) graphical Java 17 projects with weeks of uptime, and only ~400MB max memory usage (linux), so I don't think Java alone wouldn't cause this though)
