### ISSUE TITLE
Clean up tmp-folders.

### ISSUE THREAD

**Issue by aengelke** [benfry/processing4#529]
It'd be nice if Processing would delete unused tmp-folders. (After 1 month of use I had more than 1000 folders!)

**Comment by mckennapsean** [comment]
...or perhaps create a setting for it in the PDE.

Then it can be cleared out manually with a button, or set to automatically remove older folders.

**Comment by hamoid** [comment]
Or for geeks: mount your /tmp as a ram drive. It gets cleared every time you shut down your computer, your hard drive gets a longer live, and if you export images from processing to /tmp, they get written in half the time :)

**Comment by martiSteiger** [comment]
Please notice that there are additional temp files (*.err, *.log) using MS-Windows at 
C:\Users<username>\AppData\Roaming\Processing\console  for cleaning.

!!!  In any case realizing temp-files cleaning up should be a major issue for processing v3.0 !!!

**Comment by wozhub** [comment]
Processing: Flooding /tmp dir since 2013.

I made my own workaround. An sh script that changes the temporary files folder using an alias, and removes inactive files.

Download this [gist](https://gist.github.com/wozhub/60c438bc70cc9d41fde0c0b159ab877f) and place it on processing root folder.

Add the following line once the processing script establishes the APPDIR, right below "log APPDIR". 
`. $APPDIR/tmpDirFix.sh`

**Comment by geoffreyvd** [comment]
Still not fixed, I looked in my temp folder today and saw hundreds of processing folders. They are atleast 8 months old

**Comment by benfry** [comment]
Resolved for Processing 4.0 with https://github.com/processing/processing4/commit/ae874f6ef7583461c7613384bb829275e5779f25.

There is now a `temp.days` (and `console.temp.days`) entry in `preferences.txt` that determines how many days the files should be kept around. Files and folders that are modified earlier than that time span will be moved to the Trash or Recycle Bin (if available) or simply deleted.

The delay in implementation is that this has to be done carefully—anything that involves deleting files is especially scary. The With the ability to move things to the Trash/Recycle Bin we're at least a little safer. But the software has millions of downloads, and so that's a lot of machines where something bad can happen.
