### ISSUE TITLE
`surface` methods get too much use, move into the API

### ISSUE THREAD

**Issue by benfry** [benfry/processing4#53]
We've been surprised at how much `frame.setResizable()` and `frame.setTitle()` and others are being used, and we should make them into real API. 

The switch from `frame` to `surface` between 2.x and 3.x was bumpier as a result. 

Need to clean this up and get better behaviors for all of them: 

* `setSize()` is erratic across renderers
* `setResizable()` can we make this a one-time operation in `settings()`? 
* `setTitle()` is often used to output the fps of an app (a terrible idea, but there we are) so needs to happen at any time (or limited to `settings()` to prevent that usage)

**Comment by knupel** [comment]
Hi, @benfry what you mean by move `surface.setSize()` in API. If this option is choice. There will be no more possibility to use it in code ? or you mean create a specific Processing methode to call it ? like `surface.setSize()` became simply `setSize()` I hope you think about this lastoption, because like you have wrote I use a lot `surface.setSize()` and `surface.setTitle()` in my code.   By the way congratulation for the time you take to keep Processing up to date with @sampottinger.

**Comment by benfry** [comment]
@StanLepunK No, the opposite of that. They were left in the `surface` class because they weren't expected to be used much. Because they get used a lot, we should make them more official than having to introduce this weird `surface` thing to everyday users, i.e just `resize()` instead of `surface.setSize()` or something like that.

**Comment by knupel** [comment]
@benfry "ouf", like will said french guy like me.  But I see there is already method `public void setSize(int wide, int high)` in `public class PSurfaceAWT extends PSurfaceNone` I never use it, it don't work ? I ask because here i'm at this time I cannot use Processing :( If something must be coded, this class is it a place to do ?
