### ISSUE TITLE
Processing 4.01 does not start when I double click the .exe file

### ISSUE THREAD

**Issue by Talsac1001** [benfry/processing4#541]
When I double-click the processing.exe file nothing happens. This is version 4.01 I am running Windows 10 64 bit.
 

## Steps to Reproduce

1.
2.
3.

## Your Environment

 

* Processing version:
* Operating System and OS version:
* Other information:

**Comment by ScottJWalter** [comment]
I'm seeing the same behavior, whether double-clicking or trying to launch from a command window.  No error messages generated, no output at all.  Can't trace it any farther without guidance.

**Comment by Eivaso** [comment]
I have the same issue. I believe this is a reaction from Windows Defender, check your threat log.

Unfortunately for me, this means I cannot do anything about it other than running an older version of Processing, as I do not have admin access.

Update:
Running "processing.exe" is halted by Windows Defender for suspicion of a trojan virus. Some Windows computers that lack admin access will simply stop the program from running without any warnings or pop-ups. Though I wouldn't bypass this warning as I'm suspicious of running this latest version at all.

**Comment by Eivaso** [comment]
This is the same as: https://github.com/processing/processing4/issues/540#issue-1346107084
Though there is no 24. Aug. update as far as I can see.

**Comment by sidec** [comment]
The last working Processing4 release is suddenly [Processing 4.0 beta 9](https://github.com/processing/processing4/releases/tag/processing-1284-4.0b9).  Windows Defender prevents from downloading and running any of the newer one. 

Operating System and OS version
Windows 11 for x64-based Systems with update KB5016691 (2022-08)

**Comment by 94wogus** [comment]
same here

**Comment by sidec** [comment]
Any way, the solution for me was to change, at least for time being, anti-virus provider for one of available free solutions. Also, I submitted processing-4.0.1-windows-x64.zip to be reviewed by Microsoft for false positive detection. 
I guess this issue is the derivative of what @benfry is talking about in [troubleshootings](https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans) and linked to #25 
Certificates cost obviously money but I found in this [stackoverflow thread](https://stackoverflow.com/questions/252226/signing-a-windows-exe-file) one user mentioning cheap and rather reputable service (based in EU) for OS projects.

**Comment by benfry** [comment]
Yeah, this is all as described here: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans

All we can do at the moment is submit it to Microsoft as a false positive. But even after they clear it, it sometimes goes back on their list. It's very frustrating.

How you can help:

1. Help us sort out the necessary lines we need to add to the `build.xml` file so that we can sign the software as part of the release process: https://github.com/processing/processing4/issues/25 Paying for a certificate is one thing, but finding time to implement/debug the process is another.

2. If you're running into this problem, please [submit Processing as a false positive](https://www.microsoft.com/en-us/wdsi/filesubmission). Maybe more submissions will help our cause.

**Comment by benfry** [comment]
…which is to say, if you're running into this problem, please submit it to Microsoft:

https://www.microsoft.com/en-us/wdsi/filesubmission

Maybe more submissions will help our cause.
