### ISSUE TITLE
"show sketch folder" broken for Libraries

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#548]
OSX 10.15.7

When I use "Show Sketch Folder" for Libraries like Serial or PDF Export, then I get the "Save First" dialog.
Which is not possible since they are read only.

Instead it should just show the sketch folder.

**Comment by benfry** [comment]
The bug here is that it should be treating the sketch as “untitled” and setting the default save location to be your sketchbook folder. But since it's defaulting to the read-only location where the examples are stored, it's trying to save over itself. Should be able to fix for 4.0.2.

**Comment by benfry** [comment]
I'm not able to reproduce this with the latest release. If I open a PDF example, make a minor change, and hit Save, I'm sent to the sketchbook folder to save the sketch:

<img width="979" alt="Screen Shot 2022-11-27 at 7 43 04 AM" src="https://user-images.githubusercontent.com/1623101/204136044-53cb50ea-74ad-4690-a5fd-bd3d4d0ca400.png">

That behavior handled here and should be doing the right thing: https://github.com/processing/processing4/blob/main/app/src/processing/app/Sketch.java#L860

…though file dialogs have weird OS interactions sometimes where locations don't update (even more so if you have any other system extensions installed that affect this sort of thing). macOS is particularly weird about this, but there's not much we can do there.

**Comment by benfry** [comment]
Also re-reading the original request, it seems like it may be following the intended behavior.

We don't want to show the sketch folder for a read-only sketch like a built-in example because if you break it, then it's broken until you reinstall the software. Or that any changes or save will fail because they're inside a location that's sometimes not writable (the application directory) either because of system permissions or app signing or whatever.

Further, we'll probably be moving built-in examples to `.pdez` files to decrease the file count (and disk footprint) of the Processing app when it's installed. This is a step toward preparing for that scenario, where there isn't a "sketch folder" to view.
