### ISSUE TITLE
Theme is not kept after relaunch

### ISSUE THREAD

**Issue by Matto58** [benfry/processing4#565]
## Description

When I open Processing (let's say the default theme is theme A), change to a different theme (let's call this theme B), close Processing and open it again, theme A shows instead of theme B.

## Expected Behavior

Theme B should appear after relaunch instead of theme A.

## Current Behavior

Theme A appears after relaunch instead of theme B.

## Steps to Reproduce

1. Open Processing
2. Change theme
3. Close Processing
4. Open Processing again

## Your Environment

 

* Processing version: 4.0.1
* Operating System and OS version: Windows 10 21H2
* Other information:

**Comment by Matto58** [comment]
# UPDATE
I'm so stupid lmao. Steps to fix:
1. Open Tools -> Theme Selector
  ![p4-image1](https://user-images.githubusercontent.com/60749494/193451182-4390f6bd-637e-4b20-837a-abdd3485280e.jpg)
2. Choose your theme (I like this one)
  ![p4-image2](https://user-images.githubusercontent.com/60749494/193451300-a3e34328-8a68-42fe-87fc-9e01b33efc3e.jpg)
3. The theme should apply.
  ![p4-image3](https://user-images.githubusercontent.com/60749494/193451353-319cf172-b637-462d-ace7-1243fdce4ebd.jpg)
4. Click on "-> Save theme.txt to sketchbook for editing"
  ![p4-image4](https://user-images.githubusercontent.com/60749494/193451457-d7426c58-6778-43e4-b2f3-e6c05bcd8d41.jpg)
5. Bada-bing-bada-boom, you can relaunch Processing while keeping in mind that your theme won't be lost!

**Comment by benfry** [comment]
Not stupid at all—that should be working without you having to save the theme file explicitly like that.

Is there something that might be resetting your preferences file when you restart? i.e. is this a public or school lab machine?

**Comment by benfry** [comment]
Comment from @Matto58 in https://github.com/processing/processing4/issues/590:

> its my own computer that i had for years now that i use for my personal stuff

Apologies, I thought I'd unlocked this one when I reopened it. 

If you remove the `theme.txt` file and restart, are you able to select a different theme and have it stick? In past releases, the only way to set the theme was to write that file, but changes were made to no longer require it. So I'm just trying to figure out what might be going wrong. (If you're using a beta instead of 4.0.1, that would do it too…)

**Comment by Matto58** [comment]
> (If you're using a beta instead of 4.0.1, that would do it too…)

FYI: I am using a non-beta version

Here's before I delete it:
![Screenshot 2022-11-11 191323](https://user-images.githubusercontent.com/60749494/201403764-b5716f2b-8659-4144-88e0-1eed780a5fa0.jpg)

Here's after I delete and restart:
![Screenshot 2022-11-11 191656](https://user-images.githubusercontent.com/60749494/201403884-f9c5b208-d2c5-4a4b-84d1-856d14d7bc64.jpg)

Here's after I set a new theme without explicitely saving `theme.txt`:
![Screenshot 2022-11-11 191905](https://user-images.githubusercontent.com/60749494/201403955-0380f568-cbad-4668-8ae8-0093570a44f3.jpg)

And here's after a restart:
![Screenshot 2022-11-11 191931](https://user-images.githubusercontent.com/60749494/201404097-862ba731-f5e9-4a5d-8abc-cc9a2f742fbc.jpg)

**Comment by benfry** [comment]
If you change any other settings, do they remain set after a restart? (i.e. change the font size in Preferences; what happens?)

**Comment by Matto58** [comment]
Here's before I change my font size:
![image](https://user-images.githubusercontent.com/60749494/201461159-93db8c78-30e3-4c25-82df-2c6273d6188a.png)

Here's after I change it:
![image](https://user-images.githubusercontent.com/60749494/201461168-e60db5a1-7ba3-41b6-8a9a-e6991d2b3739.png)

And here's after a restart:
![image](https://user-images.githubusercontent.com/60749494/201461174-90781295-6cf4-45de-80c2-6b3df142a991.png)

So to answer your question: Nope.

**Comment by Matto58** [comment]
Just checking - is this being worked on? Sorry if I'm being a little rude!

**Comment by benfry** [comment]
At the moment I don't have anything to work on—I can't reproduce the problem. The theme is stored in the preferences file, so I was asking about changing other preferences to see if it was a problem there. Since those preferences are working, I'm stumped because I can't find another machine that has the issue. I've tried 3 that I use for testing and all of them are working fine. 

If anyone else runs into this problem and can shed some light, please help—I'd obviously like to fix it but there's nothing to fix at the moment.

**Comment by benfry** [comment]
One more thing to check: after you change the theme, check `preferences.txt` (the location for the file is listed in the Preferences window) for the line that starts with `theme=`. It should read something like `theme=Minerals/kyanite.txt` (though that's the default, so hopefully it reads something different). 

Next, look for a folder named `theme` in your Processing installation, and make sure the specified file is still there. For instance, for `Minerals/kyanite.txt` that means that there's a folder called `Minerals` inside `theme`, and that inside `Minerals` is a file named `kyanite.txt`.

**Comment by Zetrypio** [comment]
I can have the exact same problem.

I have found the cause of the problem on my machine: Preferences are not saved at all when closing the window with the close button on the right of the window title bar or by using `Alt-F4`, however they are correctly saved when closing with Menu bar -> File -> Quit or `Ctrl-Q`. I have verified that with `preferences.txt`.
I think the save method of the Preferences is not executed in the first situation.

I am using:
 - Processing version: 4.0.1
 - Operating System and OS version: Windows 10 22H2

**Comment by benfry** [comment]
Thanks, that's helpful… With that, I can at least have it explicitly save the preferences each time there's a theme change. It's overkill but better than it being sometimes broken. 

That fix is in the source, so it'll be in the next release (4.0.3 or 4.1) when available. Or if you'd like to give it a try, see about building the source and let me know.

**Comment by Zetrypio** [comment]
Thanks for the fix, I think this will work for a theme change (I didn't manage to test the fix), but I want to point out that this will not solve the problem for font size (and other preferences).

**Comment by benfry** [comment]
Preferences not saving is a totally new/separate issue that I'd not heard of before. Can you file an issue for it? For the original poster here, other preferences are working fine, this is only about the theme itself not saving when changed.

**Comment by Matto58** [comment]
> For the original poster here, other preferences are working fine,

I'd like to correct you: in [this comment](https://github.com/processing/processing4/issues/565#issuecomment-1312387453), it says nope, saving other preferences don't work, as a reply to [this comment](https://github.com/processing/processing4/issues/565#issuecomment-1312189431)

**Comment by benfry** [comment]
I'm just asking for help; the Preferences issue is unrelated, so it needs to be in a separate issue.

But perhaps don't bother, because as described in https://github.com/processing/processing4/issues/565#issuecomment-1326898928, the Preferences are working correctly. Closing the Preferences without confirming (the close box or hitting ESC) is equivalent to clicking Cancel in the window.

But again, if there's a problem with Preferences that I'm missing, please open a separate issue. The originally posted problem here is fixed.

**Comment by Matto58** [comment]
Thanks for fixing it! It works in 4.1.1 now!

**Comment by benfry** [comment]
Great, happy to hear it.
