### ISSUE TITLE
Translation for traditional Chinese

### ISSUE THREAD

**Issue by codemee** [benfry/processing4#600]
Since Pricessing use 2-digit labguage code, it's not possible to distinguish language like Tranditional Chinese(zh-tw) with Simplified Chinese(zh-cn). Can we make diferent language file for these 2 languages?

**Comment by benfry** [comment]
Sure, if you'd like to add the new translation, I can look into doing the work to make it possible to use the extended codes.

**Comment by jsyeh** [comment]
I have made a translation of Traditional Chinese (zh-tw) two years ago.

https://github.com/jsyeh/PDE_zh.properties/blob/main/PDE_zh.properties

It is used in my classroom -- it had been tested by 100+ students for two years. @codemee, is it possible for you to proofread/verify/improve this translation? Therefore the translation quality will be better to integrated into Processing.

**Comment by codemee** [comment]
@benfry 

Since @jsyeh had made the traslation file for zh-tw, it seems to be the right time to make Processing using the language file according to [the 4-digit code](http://www.lingoes.net/en/translator/langcode.htm). 

@jsyeh I'll test your translation file, thanks.

**Comment by benfry** [comment]
Thanks @jsyeh, this is great. Let me see what I can do…

**Comment by benfry** [comment]
Ok, looks like we're in business for the next release (probably 4.1 since we're adding a few features like this).

<img width="529" alt="preferences" src="https://user-images.githubusercontent.com/1623101/204006172-9b221c1f-622d-434c-88e9-df2c1e2efe07.png">

and once selected:

<img width="711" alt="zh-variant-example" src="https://user-images.githubusercontent.com/1623101/204006198-fa01886a-e397-4e0a-8e41-1c3a925565e5.png">

For now, you can use it if you build from source, or let me know what platform you're on and I can see about posting a pre-release for you.

**Comment by benfry** [comment]
More details of the new translation setup arriving in 4.1: https://github.com/processing/processing4/wiki/Translations

**Comment by codemee** [comment]
Cool.
