### ISSUE TITLE
sketchPath() returns app path when run outside setup()

### ISSUE THREAD

**Issue by ertdfgcvb** [benfry/processing4#616]
sketchPath() returns the path where Processing is installed instead of the current sketch path if called before setup:

```
String a = sketchPath();

void setup() {
  String b = sketchPath();
  
  println(a);
  println(b);
}
```

* Processing version: 4.0b
* Operating System and OS version: MacOS Catalina 10.15.7

**Comment by cacheflowe** [comment]
To be fair, there are a lot of things that rely on `setup()` or `settings()` to be called before they work as intended. I'm not sure I'd call this a bug 🐛 But maybe there could be a warning if used before initialization?

**Comment by ertdfgcvb** [comment]
Yet it behaves correctly if run in a sketch without setup/draw… 
```
println(sketchPath());
```
I’d call this inconsistency a bug…

**Comment by benfry** [comment]
That's because when there's no setup/draw, the code all runs inside `setup()`… It's safe to assume that if you have `setup()` and `draw()` in your code, almost no functions will work during class initialization like that. While not ideal, the alternative is a crazy amount of code to check for all possible edge cases, which would add more complexity than it fixes.
