### ISSUE TITLE
[v4.0.2 and above] “Cannot find a class or type named ‘PApplet’” error

### ISSUE THREAD

**Issue by 12people** [benfry/processing4#626]
## Description
I’m maintaining an open-source Processing app called [FOSStriangulator](https://github.com/FOSStriangulator/FOSStriangulator) . It used to compile just fine with every Processing version I’ve tried up until Processing 4.0.2. Now, with Processing 4.0.2 and newer versions, it won’t compile, whereas with 4.0.1, it still does. With the newer versions, it’s giving me this error:

`Cannot find a class or type named “PApplet”`

It’s also giving me a range of errors, all seemingly random, such as not being able to find classes like PImage, PrintWriter, IntList, etc.

![b7ef6f81331173d25768f9451edd4f4254bd2d7b](https://user-images.githubusercontent.com/7361228/208923363-13201606-5902-43ef-8709-12bc648b36a7.jpeg)

I looked at the [4.0.2 release notes 1](https://github.com/processing/processing4/releases/tag/processing-1287-4.0.2) and I can’t see any change that might be causing the issues.

I originally posted about this [on the forum](https://discourse.processing.org/t/processing-4-0-2-and-above-giving-cannot-find-a-class-or-type-named-papplet-error/40110) and I was directed to file a bug report here.

## Expected Behavior
I was expecting the app to run without a problem, just like it does on all the Processing versions I tried before 4.0.2.

## Current Behavior
As described above, running the app on versions 4.0.2 and above gives the `Cannot find a class or type named “PApplet”` error and fails to run.

## Steps to Reproduce
1. Clone the [FOSStriangulator repository](https://github.com/FOSStriangulator/FOSStriangulator).
2. Open the project up in Processing 4.0.2 or above.
3. Run the project.

## Your Environment

 

* Processing version: 4.0.2 and above (I tried every major version)
* Operating System and OS version: macOS 13.1 on ARM; also [independently verified on Linux](https://discourse.processing.org/t/processing-4-0-2-and-above-giving-cannot-find-a-class-or-type-named-papplet-error/40110/2)

**Comment by benfry** [comment]
@sampottinger Possible preproc changes in 4.0.2 causing this?

**Comment by sampottinger** [comment]
I'll take a look @benfry!

**Comment by sampottinger** [comment]
Hey all! Sorry for the issue here @12people.

@benfry I was trying to beautify the output Java file and part of that was trying to detect if the user was importing processing.core on their own, preventing duplicate imports from being written by the preproc. So, users who manually `import processing.core.*` wont see preproc generated import statements for `processing.core` objects.

This code imports part of processing core explicitly (https://github.com/FOSStriangulator/FOSStriangulator/blob/37fb816cc70dc4315c8a26b0b0db1411b20ffb20/FOSStriangulator/DTEdge.pde#L30) but not all of it. My change (#597) was problematic if the developer uses a package from default imports under processing.core without explicitly importing it but explicitly importing something else from processing.core as the preproc wont try to write the default imports for them to prevent duplication. Thinking more on this, unless you are opposed, I would recommend just allowing the duplicated imports to be written by the preproc in this instance. Though it may lead to duplicitous code, it is most consistent with historic behavior.

This fix is implemented with #635. My apologies to both of you for the bug. @12people I have tested FOSStriangulator with my code fix and it builds successfully.

**Comment by benfry** [comment]
Great, thanks for taking a look Sam. It happens!

Merging in the fix for 4.1.2.

**Comment by 12people** [comment]
Amazing, thanks a ton!
