### ISSUE TITLE
Shape stroke should be drawn in sub-pixel space like shape fill is

### ISSUE THREAD

**Issue by PianoMastR64** [benfry/processing4#646]
Or at least I would like an option to enable it. It's my understanding that this isn't currently possible. Here's some code to make more clear what I'm talking about:

``` java
void setup() {
  size(400, 300);
  rectMode(CENTER);
}

void draw() {
  float xTravel = frameCount * 0.03;
  float sizeMult = 1.0 / (frameCount * 0.005 + 1);
  
  background(0);

  fill(63);
  noStroke();
  square(100 + xTravel, 100, 100);
  circle(250 + xTravel, 100, 100);

  noFill();
  stroke(255);
  
  square(100 + xTravel, 200, 100);
  circle(250 + xTravel, 200, 100);
  square(100 + xTravel, 200, 50 * sizeMult);
  circle(250 + xTravel, 200, 50 * sizeMult);
}
```

Notice how the outline is moving in jumps that line up with the pixel grid, and the fill moves smoothly. This effect is very apparent when ellipses are drawn small. It would be very convenient if stroke was also smooth in this way.

I tried the P2D renderer, and squares are still jumpy, even at the highest `smooth()` setting, while ellipses are more smooth. The default renderer still looks better though, and P2D lacks abilities that are essential to the project I'm doing.

**Comment by Sachin-2206** [comment]
@PianoMastR64  Sir Is this a backend code ?

**Comment by PianoMastR64** [comment]
> @PianoMastR64 Sir Is this a backend code ?

What?

**Comment by Sachin-2206** [comment]
@PianoMastR64 Sir I want to contribute in this issue. Please tell me about this more.

**Comment by Sachin-2206** [comment]
@PianoMastR64 What is the actual issue in this and tell about technology I need to solve this issue

**Comment by micycle1** [comment]
This can be fixed by changing the `KEY_STROKE_CONTROL` hint of the `java.awt.Graphics2D` renderer like so:

```
var g2 = (Graphics2D) getGraphics().getNative();
g2.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);
```

A question for @benfry would be whether `VALUE_STROKE_PURE` should be set as default by Processing.

Docs for `KEY_STROKE_CONTROL`:

> Stroke normalization control hint value -- geometry may be modified or left pure depending on the tradeoffs in a given implementation. Typically this setting allows an implementation to use a fast integer coordinate based platform rendering library, but does not specifically request normalization for uniformity or aesthetics.

The default value is `VALUE_STROKE_DEFAULT`. Here's the doc for that:

> Some implementations may be able to use an optimized platform rendering library which may be faster than traditional softwarerendering algorithms on a given platform, but which may also **not support floating point coordinates**. 

We change it to `VALUE_STROKE_PURE`. Docs:

> Stroke normalization control hint value -- geometry should be left unmodified and **rendered with sub-pixel accuracy**.

---

You can also use the `FX2D` renderer -- that seems to handle sub-pixel stokes such a hack.

**Comment by benfry** [comment]
Use `hint(ENABLE_STROKE_PURE)` to get that behavior. 

More details in the reference: https://processing.org/reference/hint_.html

It can't be the default because ~~it's drastically slower~~ it introduces new visual artifacts in other sketches, and is only needed in a minority of cases. (Edit: Updated that after seeing a note in the code about it… I thought it was only a performance issue.)

**Comment by PianoMastR64** [comment]
@benfry Thanks. I promise I tried to look for a solution before posting here. I was under the impression that it wasn't possible and needed to be implemented
