### ISSUE TITLE
[Enhancement] Extract class for perlin noise from PApplet

### ISSUE THREAD

**Issue by Minimaximize** [benfry/processing4#69]
## Description
Extract logic behind perlin noise generation from PApplet to separate class and delegate `noise(...)` methods to new class/interface.

### Benefits
- Reduce the amount of non-sketch related code from PApplet
- Facilitate the use of other noise functions in sketches, (eg, Simplex noise, Fractal noise, Custom implementations)
- Allow previously generated noise to be cached/saved in separate noiseGenerators, instead of having to regenerate/recalculate on each noise call or on updating the noise seed.

## Proposed Implementation
- Extract noise methods and fields from PApplet into `PerlinNoiseGenerator.java` 
- Extract an interface for `NoiseGenerators` eg:
```
public interface NoiseGenerator {

  float noise(float x);
  float noise(float x, float y);
  float noise(float x, float y, float z);
  // may want to consider below
  float noise(float...n); 
  
  void setSeed(long seed);
  void setDetail(int lod);
  void setDetail(int lod, float falloff);
}
```
_(I'm unsure if this should be in `processing.core` or a new package like `processing.noise`, `processing.generators`, `processing.core.noise` etc)_
- delegate `noise` methods in PApplet to implementation of `NoiseGenerator`, and add methods for setting the current `NoiseGenerator`
Alternatively, consider deprecating noise methods in favor of creating noise generators

**Comment by benfry** [comment]
This would be better handled by a library. This isn’t a compelling enough reason to break a lot of old code that relies on the noise() function as it currently exists. 

You get a little code clarity but the real point is that there are better noise methods and lots of additional features to do noise properly, which belong in their own library. And that amount of flexibility isn’t what’s needed by 80 or 90% of users.  This is why we put so much effort into making the library system work as smoothly as possible, so that features like this can be built out more thoroughly. And in cases where the majority of users want the library, we’ve incorporated that into Processing.
