### ISSUE TITLE
Centering text vertically does not work correctly

### ISSUE THREAD

**Issue by ThexXTURBOXx** [benfry/processing4#739]
## Description
`textAlign(CENTER, CENTER)` does not center text vertically correctly

## Expected Behavior
After `textAlign(CENTER, CENTER)`, text should be aligned in the center.

## Current Behavior
The text is not centered vertically:

![grafik](https://github.com/processing/processing4/assets/12763829/ab8d6db3-9783-443a-9c6b-6c4e825914ea)

## Steps to Reproduce
1. Run the following sketch:
    ```pde
    void setup() {
      size(100,100);
    }
    
    void draw() {
      background(0);
      textAlign(CENTER,CENTER);
      textSize(100);
      text("Ap", width/2, height/2);
    }
    ```

## Your Environment
* Processing version: `4.2`
* Operating System and OS version: `Windows 11 22621.1928`

## Possible Causes / Solutions

The issue lies most likely somewhere within these lines: https://github.com/processing/processing4/blob/main/core/src/processing/core/PGraphics.java#L4920-L4926
But I am not sure

**Comment by SableRaf** [comment]
Hi @ThexXTURBOXx,

Thanks for raising this issue. You're correct that Processing's vertical alignment may not center text perfectly due to the way it handles characters that extend above or below the baseline.

A potential workaround involves calculating the full height of the text, including both ascent and descent, and adjusting the y-position accordingly. However, this method is not ideal as the ascent and descent are based on the tallest and deepest characters (d and p), which may not represent the actual height of your specific string.

A more accurate workaround to get the exact string height involves generating a vector representation for each character, identifying the vertices with the highest and lowest Y positions.

I would recommend taking a look at [this excellent StackOverflow post](https://stackoverflow.com/questions/64146977/how-do-you-find-out-the-height-and-width-of-a-pfont-string-in-processing-or-java/64518397#64518397) by @micycle. It provides a detailed explanation on this matter and presents potential solutions.
