### ISSUE TITLE
[Feature request]: Option to compile to standalone jar

### ISSUE THREAD

**Issue by ghost** [benfry/processing4#765]
Ive tried creating my own compile script to compile all the processing code into just one jar file, i never got it working probably.
It would be perfect to have an option for compiling to a standalone jar.

**Comment by benfry** [comment]
This used to be the default but we had to abandon it. Primarily because the OpenGL libraries involve multiple files and components to work, and those are part of the “core,” making it nearly impossible without enormous cross-platform effort (to unpack the libraries from a JAR, make sure they can be initialized, etc). Another other reason was that as people included more assets in their sketches, build times got slower and runtime performance suffered when they were extracting those assets from the JAR file.

I believe there may be a contributed Tool that still does this, I would give that a shot!
