### ISSUE TITLE
Mode migration to Processing 4 -- tips/doc/wiki

### ISSUE THREAD

**Issue by jeremydouglass** [benfry/processing4#87]
I'm trying to get a handle on what might be involved in migrating Processing.R (and Processing.py) to P4.

I've looked briefly at  #10  #11  #13 , but without diving deep I haven't gotten a sense of where on the scale from "a few new interfaces" to "total rewrite" we might expect mode migration to be.

**Feature request:**

It would be ideal if sometime early in the P4 process there could be a P4 wiki page "mode migration" with a few key tips to get mode migrators started. That way mode migration projects could more easily get underway -- and potentially uncover problems / give feedback during alpha/beta.

**Comment by benfry** [comment]
Yup, definitely will do. Trying as hard as possible for there to be zero changes necessary, but that would also prevent us from some nicer things like swapping out `JEditSyntaxArea` for `RSyntaxArea`. 

As for expectations, I see two most likely outcomes: 

1. No changes necessary, or maybe just a recompile. 
2. More changes necessary, but only for anything previously deprecated, or any code that relies on the quirky internals of `JEditTextArea`, i.e. the piggybacking off or adding new customizations like we've done in the Editor. 

In the first case, Mode authors would still need to learn to make nice with Java 11 as it affects their code. As you can see from Sam's changes, it can be a lot.

In the second case, there are very few Modes out there, so if the second point happens, I'd set aside some time to work w/ Mode authors to do updates.

The big question at the moment is probably whether to ditch `JEditSyntax`. It'd be nice, but it's also a heavy lift for me to get everything working again, the Mode authors may be saved some work for my lack of time. (Though a worse experience for users…)

**Comment by villares** [comment]
I think I could run Python mode on an earlier alpha/pre-alpha (but maybe it was a dream). Would it be helpful to open an issue documenting the errors I get when I try it now, or will it just be noise compared to this discussion here?
I'm quite convinced it would be a bad idea, but I wouldn't want to miss the opportunity of documenting the problems early if you think it would help.

**Comment by benfry** [comment]
Oh, ha—there shouldn't actually be anything that's breaking Modes yet!

But I just took a look at Python and it seems that there's some sort of a hack in there that breaks because it's using the `frame` field that's been removed from `PApplet`: https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/PAppletJythonDriver.java#L460

Just posted an issue for it so that Jonathan is aware: https://github.com/jdf/processing.py/issues/382

Thanks for checking…

**Comment by benfry** [comment]
An update on this issue…

The `frame` issue also affects the R Mode, so I've posted a note in that repo about how to fix it. 

Also for Shader Mode, there's an issue with how a Menu is being initialized and I've posted the fix for that as well. 

Both should be fairly simple fixes, but will need a recompile. The changes *should* be backwards compatible so they won't be maintaining separate 3.x/4.x versions. 

(Leaving this open since those changes haven't happened yet.)

**Comment by benfry** [comment]
I think we're all set on this front, but for anyone building a Mode who has questions, please file a new issue with the problem and I can answer questions/fix code as needed. We only have 5 or 6 Modes so I'm fine with just supporting them here directly.
